Added Objetslitt custom catalog
catima/catalogs pull request #3
Opened 2023-08-14 16:46 UTC by florian-rieder

Added a new custom catalog for Objetslitt which contains the following features and customizations:

- Added a "Daily item" feature that uses `Rails.cache.fetch` and expires every day at midnight.
- Reorder the simple search result tabs so that the category "textes" will be shown first if available.
- Customized the home page to display a cards menu and the daily item.
- Added a custom page for the "donnees" slug, which displays a simple search form and the daily item.
- Customized the navbar when visiting the "donnees" page to show a different menu specifically for this page.
- Added a mailto icon to the navbar.
- Added logos in the footer.

2023-08-17 13:27 UTC, lucaguindani requested changes

2023-08-17 13:27 UTC, lucaguindani commented on .gitignore
Missing empty new line at the end of the file

2023-08-17 13:27 UTC, lucaguindani commented on objetslitt/views/pages/show.html.erb
Missing empty new line at the end of the file

2023-08-17 13:27 UTC, lucaguindani commented on objetslitt/views/shared/_daily_item.html.erb
Missing empty new line at the end of the file

2023-08-17 13:27 UTC, lucaguindani commented on objetslitt/views/shared/navbar/_navbar_catalog.erb
Overriding this view to add a menu for a specific page is risky... catalog could break if we make changes to the navbar and cannot backport them to the custom catalog. Maybe you could add the dropdowns **under** the navbar by overriding shared/_page_header.erb (this view contains a lot less logic than the navbar -> fewer risks of breaking) ?

Why absolute urls and not relative ? Remove all the `https://catima.unil.ch` ?

2023-08-17 13:27 UTC, lucaguindani commented on objetslitt/views/simple_searches/_list.html.erb
Also risky to override, but this is a feature we're planning to add in the future, so we can keep it like that and we will adapt the catalog when the feature is implemented for everyone.

2023-08-23 17:40 UTC, florian-rieder commented on objetslitt/views/shared/navbar/_navbar_catalog.erb
I fully understand the reasons not to override this view. Moving the custom menu for the "donnees" page to the page header is a good idea, beyond avoiding the risky override of navbar_catalog, it also helps with the accessibility and navigability of the catalog by keeping the main menu consistent for every page.

The mailto logo has been moved to the new help_menu view, which avoids overriding navbar_catalog. The absolute urls have been converted to relative.

2023-08-24 06:04 UTC, lucaguindani approved these changes

2023-08-24 06:04 UTC, merged